---
- name: Check if systemd dir exists
  stat:
    path: /etc/systemd
  register: systemd_check

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_check is success

- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
  become: true

- name: Restart Logstash
  service:
    name: logstash
    state: started
    enabled: true
  become: true

#- name: Restart Kibana
#  command: /etc/init.d/kibana start
#  become: true

- name: Restart Kibana
  service:
    name: kibana
    state: started
    enabled: true
  become: true

- name: Print SSL certificate post-setup information
  debug: msg="Filebeat SSL Certificate available at http://{{ ansible_fqdn }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.crt"

- name: Print SSL key post-setup information
  debug: msg="Filebeat SSL Certificate key is located at http://{{ ansible_fqdn }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.key"

- name: Print X-Pack instructions
  debug: msg="*** 1A) (X-Pack only) Kibana account credentials login with elastic/{{xpack_elastic_user_password}} ***"
  when: install_kibana_xpack|bool

- name: Print index creation instructions
  debug: msg="*** 1) Navigate to http://{{ ansible_fqdn }}:{{ kibana_server_port }} and login with {{kibana_user}}/{{kibana_password}} ***"
